core/urls.py
from account.views import *
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', dashboard, name='dashboard'),
    path('delete-inactive-users/', deleteInactiveUsers,
         name='delete-inactive-users'),
    path('signup/', register, name='signup'),
    path('login/', loginView, name='login'),
    path('logout/', userLogout, name='logout'),
    # path('logout/', UserLogoutView.as_view(), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>)/', activate, name='activate'),

    path('password-change/', PasswordChange.as_view(),
         name='password-change'),
    path('password-reset/', ResetPassword.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         ResetPasswordConfirm.as_view(), name='password_reset_confirm'),

    path('password-reset-complete/', ResetPasswordComplete.as_view(),
         name='password-reset-complete'),

    path('', include('logistics.urls', namespace='logistics')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Louisgistic Xpress'

logistics/urls.py
from django.urls import path
from .views import *

app_name = 'logistics'

urlpatterns = [
    path('user-shipments/', UserShipments.as_view(), name='shipments'),
    path('all-shipments/', AllShipments.as_view(), name='all-shipments'),
    path('shipment-detail/', trackShipment, name='shipment-detail'),
    path('add-shipment/', AddShipment.as_view(), name='add-shipment'),
    path('contact-us/', ContactView.as_view(), name='contact-us'),
    path('delete-shipment/<slug:slug>/delete/',
         deleteShipment, name='delete-shipment'),
    path('update-shipment/<slug:slug>/',
         UpdateShipment.as_view(), name='update-shipment'),
    path('', IndexView.as_view(), name='home'),

]

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <meta name="description" content="{% if desc %}{{desc}}{% else %}LP Logistics gets your deliveries covered{% endif %} " />
    <link rel="stylesheet" href="{% static '/css/resets_classes.css' %}" />
    <link rel="stylesheet" href="{% static '/css/fonts.css' %}" />
    <link rel="stylesheet" href="{% static '/css/styles.css' %}" />
    <link rel="stylesheet" href="{% static '/css/media-queries.css' %}" />
    
    <title>{% if title %}{{title}}{% else %}LP Logisticz{% endif %}</title>
  </head>
  
  <body id="body-id">

    <span class="scrolltop" id="scroll-top" onclick="scrollToTop()">&uarr;</span>

    {% block header %} 
    {% endblock header %}
    
    {% block modal %} 
    {% endblock modal %}

    <main>
      
      {% block content %} 
      {% endblock content %}

    </main>
    
    
    {% include 'footer.html' %} 
    
    <script src="{% static 'js/core.js' %}"></script>
    {% block js %} 
    
    {% endblock js %}

  </body>
</html>

templates/footer.html
{% load static %} 
<footer>
  <div class="inner-container footer-contents">
    <div class="footer-grids">

      <div class="footer-grid">
        <h5>COMPANY</h5>
        <ul>
          <li><a href="">About Us</a></li>
          <li><a href="">FAQ</a></li>
          <li><a href="">Company</a></li>
          <li><a href="">Privacy Policy</a></li>
          <li><a href="">Customer Services</a></li>
        </ul>
      </div>

      <div class="footer-grid">
        <h5>OPEN HOUR</h5>
       <ul>
         <li><a href="">Monday 11am-7pm</a></li>
         <li><a href="">Tuesday-Friday 11am-8pm</a></li>
         <li><a href="">Saturday 10am-6pm</a></li>
         <li><a href="">Sunday 11am-6pm</a></li>
         <li><a href="">Holidays 12am-5pm</a></li>
       </ul>
      </div>

      <div class="footer-grid">
        <h5>RESOURCES</h5>
        <ul>
          <li><a href="">Home insurance</a></li>
          <li><a href="">Travel insurance</a></li>
          <li><a href="">Car insurance</a></li>
          <li><a href="">Business insurance</a></li>
          <li><a href="">Heal insurance</a></li>
        </ul>
      </div>
      <div class="footer-grid">
        <a href="{% url 'logistics:home' %}" class="nav-logo">
          <img src="{% static 'img/icons/icons8-in-transit-40.png' %}" alt="logo img" srcset="">
          <div class="logo-name">
            <p>LOUISGISTIC</p>
            <h2>XPRESS</h2>
          </div>
        </a>
        <p class="para">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi cum id soluta veniam cupiditate.</p>
        <div class="social-icons">
          <a href="http://" target="_blank" rel="noopener noreferrer">
            <img src="{% static '/img/icons/facebook-48.png' %}" alt="" srcset="">
          </a>
          <a href="http://" target="_blank" rel="noopener noreferrer">
            <img src="{% static '/img/icons/icons8-instagram-48.png' %}" alt="" srcset="">
          </a>
          <a href="http://" target="_blank" rel="noopener noreferrer">
            <img src="{% static '/img/icons/twitter-48.png' %}" alt="" srcset="">
            
          </a>
        </div>
      </div>

      </div>
      <div class="copyright">
        <p>Copyright © 2021 - <span class="year-span"></span> all Rights reserved Xpress. Built by ThinkingTek Industries </p>
      </div>
    </div>
  </div>
</footer>

templates/form_base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/fonts.css' %}" />
    <link rel="stylesheet" href="{% static '/css/resets_classes.css' %}" />
    <link rel="stylesheet" href="{% static '/css/forms.css' %}" />
    {% if title %}
      <title>{{title}}</title>
    {% else %}
    <title>Logistics Webapp</title>
    {% endif %}
</head>
<body>
    <main class="overlay-bg">
        <div class="form-container">
            {% include 'notify.html' %}
            {% block form %}  

            {% endblock form %}
        </div>
    </main>
    <script src="{% static '/js/forms.js' %}"></script>
</body>
</html>

templates/home-header.html
{% include 'nav.html' %}
<header class="home_header overlay-bg">
  <div class="showcase">
    <div class="inner-container">
      <h2>Safe and Relaiable <span>Logistics</span> Solutions</h2>
      <form action="{% url 'logistics:shipment-detail' %}" method="GET" class="tracking-form">
        {% csrf_token %}
        <div class="form-inputs">
          {{form.track_id}}
          {% if form.track_id.errors %}

          {% for error in form.track_id.errors %}
          <p class="error">{{error}}</p>
          {% endfor %}
        
          {% endif %}
        </div>
        <button type="submit">TRACK</button>
      </form>
    </div>
  </div>
</header>

templates/nav.html
{% load static %}
{% load template_tags %}
  <nav class="header_navbar">
    <div class="navbar_container flex_center_btw">

      <div class="logo_name ">
        <a href="{% url 'logistics:home' %}" class="logo_link flex_center">
          <img src="{% static 'img/icons/icons8-in-transit-40.png' %}" alt="logo img" srcset="">
          <div class="logo-name">
            <p>LOUISGISTIC</p>
            <h2>XPRESS</h2>
          </div>
        </a>
      </div>
  
      <ul class="navbar_ul">
        <li class="navbar_li">
          <a href="{% url 'logistics:home' %}" class="nav_links {% if home_active %} active {% endif %}">Home</a>
        </li>
        <li class="navbar_li">
          <a href="{% url 'logistics:contact-us' %}" class="nav_links {% if contact_active %} active {% endif %}">Contact Us</a>
        </li>
        {% if user.is_authenticated %}
        {% if user|has_group:"staff" %}
        <li class="navbar_li">
          <a href="{% url 'logistics:add-shipment' %}" class="nav_links {% if add_shipment_active %} active {% endif %}">Add Shipment</a>
        </li>
        <li class="navbar_li">
          <a href="{% url 'logistics:all-shipments' %}" class="nav_links {% if shipments_active %} active {% endif %}">Shipments</a>
        </li>
        <li class="navbar_li">
          <a href="{% url 'dashboard' %}" class="nav_links {% if dashboard_active %} active {% endif %}">Dashboard</a>
        </li>
        {% endif %}
        <li class="navbar_li">
          <a href="{% url 'logout' %}" class="nav_links auth-link">Logout</a>
        </li>
        {% else %}
        <li class="navbar_li">
          <a href="{% url 'login' %}" class="nav_links auth-link">Sign~in</a>
        </li>
        {% endif %}
      </ul>

      <div class="nav_toggle" id="nav-toggle" onclick="toggle_sidebar()">
        <img src="{% static 'img/icons/icons8-menu-50-orange.png' %}" alt="" class="img-toggle">
      </div>
    </div>

  </nav>

templates/notify.html
{% for message in messages %}
<div class="inner-container message-alert alert-{{message.tags}} alert">
  <div class="toggle-btn alert-{{message.tags}}" onclick="removeAlert()">X</div>
  <div class="message">{{message}}</div>
</div>
{% endfor %}