core/urls.py
from account.views import *
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', dashboard, name='dashboard'),
    path('delete-inactive-users/', deleteInactiveUsers,
         name='delete-inactive-users'),
    path('signup/', register, name='signup'),
    path('login/', loginView, name='login'),
    path('logout/', userLogout, name='logout'),
    # path('logout/', UserLogoutView.as_view(), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>)/', activate, name='activate'),

    path('password-change/', PasswordChange.as_view(),
         name='password-change'),
    path('password-reset/', ResetPassword.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         ResetPasswordConfirm.as_view(), name='password_reset_confirm'),

    path('password-reset-complete/', ResetPasswordComplete.as_view(),
         name='password-reset-complete'),

    path('', include('logistics.urls', namespace='logistics')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Louisgistic Xpress'

logistics/urls.py
from django.urls import path
from .views import *

app_name = 'logistics'

urlpatterns = [
    path('user-shipments/', UserShipments.as_view(), name='shipments'),
    path('all-shipments/', AllShipments.as_view(), name='all-shipments'),
    path('shipment-detail/', trackShipment, name='shipment-detail'),
    path('add-shipment/', AddShipment.as_view(), name='add-shipment'),
    path('contact-us/', ContactView.as_view(), name='contact-us'),
    path('delete-shipment/<slug:slug>/delete/',
         deleteShipment, name='delete-shipment'),
    path('update-shipment/<slug:slug>/',
         UpdateShipment.as_view(), name='update-shipment'),
    path('', IndexView.as_view(), name='home'),

]

logistics/models.py
from typing import Iterable
from django.db import models
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from logistics.imports.choices import *
from django.utils.text import slugify
User = get_user_model()


class Shipment(models.Model):
    staff = models.ForeignKey(
        User, related_name='staff', on_delete=models.DO_NOTHING)
    updated_staff = models.ForeignKey(
        User, related_name='updated_staff', on_delete=models.DO_NOTHING)
    tracking_id = models.CharField(max_length=15, blank=True)
    slug = models.SlugField(max_length=260, blank=True, unique=True)
    email = models.EmailField(blank=True, null=True)
    sender_name = models.CharField(verbose_name='Full name', max_length=30)
    sender_phone = models.CharField(max_length=14)
    city_of_origin = models.CharField(max_length=20)
    state_of_origin = models.CharField(
        max_length=15, choices=STATES)
    reciever_phone = models.CharField(max_length=14)
    reciever_address = models.CharField(verbose_name='Address', max_length=90)
    reciever_name = models.CharField(verbose_name='Full_name', max_length=30)
    status = models.CharField(
        max_length=15, choices=STATUS, default="packaging", blank=True)
    destination_city = models.CharField(max_length=20)
    destination_state = models.CharField(max_length=15, choices=STATES)
    transport_method = models.CharField(
        max_length=15, choices=TRANSPORT_METHOD)
    substance_type = models.CharField(
        max_length=15, choices=SUBSTANCE_TYPE)
    unit_of_measurement = models.CharField(
        max_length=15, choices=UNIT_OF_MEASUREMENT)
    units = models.DecimalField(max_digits=20, decimal_places=1)
    request_refund = models.BooleanField(default=False)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)
    desc = models.TextField()

    def save(self):
        self.slug = slugify(self.tracking_id)
        super().save()

    class Meta:
        ordering = ['-created_timestamp']

    def get_absolute_url(self):
        return reverse("logistics:update-shipment", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("logistics:update-shipment", kwargs={"slug": self.slug})

    def __str__(self):
        return self.sender_name

logistics/forms.py
from django import forms
from logistics.models import *
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages
from logistics.imports.choices import EMAIL_SUBJECTS


class TrackFrom(forms.Form):
    track_id = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Tracking ID'}))

    class Meta:
        fields = ["track_id"]

    def clean(self):
        track_id = self.cleaned_data.get("track_id")
        try:
            shipment = Shipment.objects.get(tracking_id=track_id)
            if shipment:
                pass

        except Shipment.DoesNotExist:
            raise forms.ValidationError('Incorrect tracking ID.')
            # return redirect(reverse('logistics:shipment-detail', {'shipment': shipment}))
        return track_id


class AddShipmentForm(forms.ModelForm):
    reciever_address = forms.CharField(max_length=90, widget=forms.TextInput(
        attrs={'placeholder': 'Receiver Address'}))
    sender_name = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Full name'}))
    sender_phone = forms.CharField(min_length=11, max_length=14, widget=forms.TextInput(
        attrs={'placeholder': ' Phone'}))
    email = forms.EmailField(required=False, widget=forms.EmailInput(
        attrs={'placeholder': 'Email Address'}))
    city_of_origin = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'placeholder': 'City of Departure'}))

    reciever_name = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Full name'}))
    reciever_phone = forms.CharField(min_length=11, max_length=14, widget=forms.TextInput(
        attrs={'placeholder': 'Phone'}))
    destination_city = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'placeholder': 'City of Destination'}))
    units = forms.DecimalField(widget=forms.NumberInput(
        attrs={'placeholder': 'Units'}))

    desc = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Additional details about this shipment...',
        'rows': 4,
    }))

    class Meta:
        model = Shipment
        fields = "__all__"
        exclude = ('staff', 'updated_staff', 'request_refund',
                   'created_timestamp', 'update_timestamp', 'status', 'slug', 'tracking_id')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['substance_type'].empty_label = 'Liquid/Solid'
        self.fields['unit_of_measurement'].empty_label = 'Kg / Lbs'
        self.fields['transport_method'].empty_label = 'Transport method'
        self.fields['state_of_origin'].empty_label = 'Choose State'
        self.fields['destination_state'].empty_label = 'Choose State'


class UpdateShipmentForm(forms.ModelForm):
    sender_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Fullname'}))
    sender_phone = forms.CharField(max_length=12, widget=forms.TextInput(
        attrs={'placeholder': ' Phone'}))
    email = forms.EmailField(required=False, widget=forms.EmailInput(
        attrs={'placeholder': 'Email Address'}))
    city_of_origin = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'City of Departure'}))

    reciever_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Fullname'}))
    reciever_phone = forms.CharField(max_length=12, widget=forms.TextInput(
        attrs={'placeholder': 'Phone'}))
    destination_city = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'City of Destination'}))
    units = forms.DecimalField(widget=forms.NumberInput(
        attrs={'placeholder': 'Units'}))

    desc = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Additional details about this shipment...',
        'rows': 4,
    }))

    class Meta:
        model = Shipment
        fields = "__all__"
        exclude = ('staff', 'updated_staff',
                   'request_refund', 'created_timestamp', 'update_timestamp', 'slug', 'tracking_id')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['substance_type'].empty_label = 'Liquid/Solid'
        self.fields['unit_of_measurement'].empty_label = 'Kg / Lbs'
        self.fields['transport_method'].empty_label = 'Transport method'
        self.fields['state_of_origin'].empty_label = 'Choose State'
        self.fields['destination_state'].empty_label = 'Choose State'


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        'placeholder': "Firstname"
    }))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        'placeholder': "Lastname"
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': "Your Email Address"
    }))
    subject = forms.ChoiceField(choices=EMAIL_SUBJECTS)
    message = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': "Type in your message"
    }))

logistics/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .forms import *
from .models import *
from .mixins import *
from .utils import create_ref_code
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView, FormView


def trackShipment(request):
    if request.method == "GET":
        form = TrackFrom(request.GET)
        track_id = request.GET.get('track_id')
        shipment = None
        if track_id:
            try:
                shipment = Shipment.objects.get(tracking_id=track_id)
            except Shipment.DoesNotExist:
                pass
                # messages.error(request, "Incorrect tracking ID")

    context = {'shipment': shipment, 'form': form}
    return render(request, 'logistics/shipment-detail.html', context)


class IndexView(FormView):
    form_class = TrackFrom
    template_name = 'logistics/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Louisgistics Xpress | Homepage'
        context['home_active'] = True
        return context


class AddShipment(LoginRequiredMixin, StaffUserMixin, CreateView):
    model = Shipment
    form_class = AddShipmentForm
    success_url = reverse_lazy('logistics:add-shipment')
    template_name = 'logistics/addshipment.html'

    def form_valid(self, form):
        sender_name = f"{form.cleaned_data.get('sender_name').title()}"
        reciever_name = f"{form.cleaned_data.get('reciever_name').title()}"

        form.instance.staff = self.request.user
        form.instance.updated_staff = self.request.user
        form.instance.tracking_id = create_ref_code()
        messages.success(
            self.request, f"{sender_name} shipment has been registered successfully")

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_btn'] = 'Submit'
        context['add_shipment_active'] = True
        context['title'] = 'Add Shipment'
        return context


class UpdateShipment(LoginRequiredMixin, StaffUserMixin, UpdateView):
    model = Shipment
    form_class = UpdateShipmentForm
    template_name = 'logistics/addshipment.html'

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER', super().get_success_url())

    def form_valid(self, form):
        sender_name = f"{form.cleaned_data.get('sender_name').title()}"
        reciever_name = f"{form.cleaned_data.get('reciever_name').title()}"

        form.instance.updated_staff = self.request.user
        messages.success(
            self.request, f"{sender_name} shipment has been updated successfully")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        shipment = self.get_object()
        context = super().get_context_data(**kwargs)
        context['shipment'] = shipment
        context['submit_btn'] = 'Update'
        context['add_shipment_active'] = True
        context['title'] = 'Update Shipment'
        return context


class AllShipments(LoginRequiredMixin, StaffUserMixin, ListView):
    paginate_by = 35
    context_object_name = 'shipments'
    template_name = 'logistics/shipments.html'
    queryset = Shipment.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "All Shipments"
        context['empty_txt'] = "You've not registered any shipment."
        context['shipments_active'] = True
        context['all_shipment_active'] = True
        context['txt_writeup'] = "All shipments registered by all staffs"
        return context


class UserShipments(LoginRequiredMixin, StaffUserMixin, ListView):
    paginate_by = 35
    context_object_name = 'shipments'
    template_name = 'logistics/shipments.html'

    def get_queryset(self):
        return Shipment.objects.filter(staff=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"{self.request.user.first_name} | Shipments"
        context['empty_txt'] = "No shipment registered."
        context['user_shipment_active'] = True
        context['txt_writeup'] = "Here are some shipments you've registered"
        return context


class ContactView(FormView):
    form_class = ContactForm
    template_name = 'logistics/contact.html'
    success_url = reverse_lazy('logistics:contact-us')

    def form_valid(self, form):
        messages.info(
            self.request, "Thanks for getting in touch with us, we receieved your message.")
        first_name = form.cleaned_data.get('first_name')
        last_name = form.cleaned_data.get('last_name')
        email = form.cleaned_data.get('email')
        message = form.cleaned_data.get('message')
        full_name = f'{first_name} {last_name}'

        full_message = f"""
         Recieved message below from {full_name}, {email}
         ____________________________________
         {message}
        """
        send_mail(
            subject='Recieved contact us information',
            message=full_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.NOTIFY_EMAIL]
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Louisgistics | Contact Us'
        context["contact_active"] = True
        return context


@login_required
def deleteShipment(request, slug):
    shipment = get_object_or_404(Shipment, slug=slug)
    if request.user == shipment.staff:
        shipment.delete()
        messages.info(request, f'Shipment deleted')
        return redirect(request.META.get('HTTP_REFERER', '/'))
    return redirect('logistics:home')

logistics/templates/logistics/addshipment.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
  <link rel="stylesheet" href="{% static 'css/resets_classes.css' %}">
  <link rel="stylesheet" href="{% static 'css/addshipment.css' %}">
  <link rel="stylesheet" href="{% static 'css/media-queries.css' %}">
  <title>{% if title %}{{title}}{% else %}Shipment Form{% endif %}</title>

</head>
<body>
  <div class="shipment-container overlay-bg">
    <div class="form-container">
      {% include 'notify.html' %}
      <form action="" method="POST">
        {% csrf_token %}
        <h4>Sender Information 
          <span class="lastly-updated">
          {% if shipment.updated_staff != shipment.staff and shipment.created_timestamp < shipment.updated_timestamp %}
          | Lastly updated by: &laquo{{shipment.updated_staff}}&raquo {{shipment.updated_timestamp|timesince}} ago
          {% endif %}
        </span>
        </h4>
        <div class="input-container grid-column-three">
          <div class="form-inputs">
            {{form.sender_name}}
          </div>
          <div class="form-inputs">
            {{form.sender_phone}}
            {% for errors in form.sender_phone.errors %}
            <p class="errors">{{errors}}</p>
            {% endfor %}
          </div>
          <div class="form-inputs">
            {{form.email}}
            {% for errors in form.email.errors %}
            <p class="errors">{{errors}}</p>
            {% endfor %}
          </div>
        </div>

        <div class="input-container grid-column-two">
          <div class="form-inputs">
            {{form.city_of_origin}}
            {% for errors in form.city_of_origin.errors %}
            <p class="errors">{{errors}}</p>
            {% endfor %}
          </div>
          <div class="form-inputs">
            {{form.state_of_origin}}
          </div>
        </div>
        
        <h4>Reciever Information</h4>
        <div class="input-container">
          <div class="form-inputs">
            {{form.reciever_address}}
          </div>
        </div>
        <div class="input-container grid-column-two">
          <div class="form-inputs">
            {{form.reciever_name}}
          </div>
          <div class="form-inputs">
            {{form.reciever_phone}}
            {% for errors in form.reciever_phone.errors %}
            <p class="errors">{{errors}}</p>
            {% endfor %}
          </div>
        </div>
        <div class="input-container grid-column-two">
          <div class="form-inputs">
            {{form.destination_city}}
            {% for errors in form.destination_city.errors %}
            <p class="errors">{{errors}}</p>
            {% endfor %}
          </div>
          <div class="form-inputs">
            {{form.destination_state}}
          </div>
        </div>

        <h4>Shipment Information</h4>
        <div class="input-container grid-column-four">
          <div class="form-inputs">
            {{form.transport_method}}
          </div>
          <div class="form-inputs">
            {{form.substance_type}}
          </div>
          <div class="form-inputs">
            {{form.unit_of_measurement}}
          </div>
          <div class="form-inputs">
            {{form.units}}
          </div>
        </div>
        {% if form.status %}
        <div class="input-container">
          <div class="form-inputs">
            {{form.status}}
          </div>
        </div>
        {% endif %}

        <div class="input-container">
          <div class="form-inputs">
            {{form.desc}}
          </div>
        </div>
        <div class="input-container">
          <div class="form-inputs">
            <button type="submit">{{submit_btn}}</button>
          </div>
        </div>
        <div class="input-container">
          <div class="form-inputs">
            {% for error in form.non_field_errors %}
            <p class="errors">{{error}}</p>
            {% endfor %}
          </div>
        </div>
        
      </form>
      <div class="links-tabs">
        <a href="{{request.META.HTTP_REFERER}}">&laquo; Back</a>
        <a href="{% url 'logistics:shipments' %}">shipments</a>
        <a href="{% url 'logistics:add-shipment' %}"> Add shipment</a>
        <a href="{% url 'logistics:home' %}">Home</a>
    </div>
  </div>
  
</body>

  <script src="{% static 'js/core.js' %}"></script>
</html>

logistics/templates/logistics/contact.html
{% extends 'base.html' %} 
{% load static %} 
{% block header %} 
{% include 'nav.html' %}
{% endblock header %} 

{% block content %}




<div class="inner-container contact-form">
    {% if messages %}
      {% include 'notify.html' %}
    {% endif %}
  <h3>Contact information</h3>
  <div class="contact-info">

    <div>
      <img src="{% static '/img/icons/place-marker-30.png' %}" alt="" srcset="">
      <a href="http://">Area 1, Abuja</a>
    </div>

    <div>
      <img src="{% static '/img/icons/phone-30.png' %}" alt="" srcset="">
      <a href="tel://1234567920">+2347018739335</a>
    </div>

    <div>
      <img src="{% static '/img/icons/send-email-30.png' %}" alt="" srcset="">
      <a href="mailto:">thinkingtek24@gmail.com</a>
    </div>
    <div>
      <img src="{% static '/img/icons/globe-earth-30.png' %}" alt="" srcset="">
      <a href="{% url 'logistics:home' %}">Louisgistics Xpress </a>
    </div>
  </div>

  <div class="contact-form-container">
    <h4>Get in touch</h4>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="form-div grids">
        {{form.first_name}}
        {{form.last_name}}
      </div>
      <div class="form-div grids">
        {{form.subject}}
        {{form.email}}
      </div>
      <div class="form-textarea">
        {{form.message}}
      </div>
      <button type="submit">Send Message</button>
    </form>
  </div>
</div>

{% endblock content %}

logistics/templates/logistics/shipments.html
{% extends 'base.html' %} 
{% load static %} 

{% block header %} 
{% include 'nav.html' %}
<div class="page-details overlay-bg">
  <div class="inner-container details">
      <h4>#Shipments</h4>
      <p>
        <span><img class="" src="{% static 'img/icons/icons8-shipment-50-fill-white.png' %}" alt="" srcset=""></span>
        <span>Manage shipments</span>
      </p>
  </div>
</div>
{% endblock header %} 

{% block modal %} 
  <div class="d-none modalbox">
    <div class="delete-modal">
      <p>Are you sure you want to delete this Shipment <span id="refCode">"hsjhdjhdd6636"</span> ?</p>
      <div class="btn-container">
        <a href="" id="deleteShipmentLink">Delete</a>
        <button type="button" onclick="closeModal()">Cancel</button>
      </div>
    </div>
  </div>
{% endblock modal %}

{% block content %}
<div class="inner-container">
  {% include 'notify.html' %}
</div>

<div class="inner-container">
  <div class="crum-container">
    <a  href="{% url 'dashboard' %}">Account / </a> 
    <a class="{% if user_shipment_active %}active{% endif %}" href="{% url 'logistics:shipments' %}">my Shipments / </a> 
    <a class="{% if all_shipment_active %}active{% endif %}" href="{% url 'logistics:all-shipments' %}">All Shipments / </a> 
    <a href="{% url 'logistics:home' %}">Contact Us / </a> 
    <span class="crum-tags">{{user.email}}</span>
  </div>
</div>

<div class="inner-container dashboard">
  <h3 class="wlc-user">Welcome {{user.first_name|title}}</h3>
  <p class="mb-1">{{txt_writeup}}</p>

  <div class="shipment_table">

    <div class="web_table">
      <table cellspacing=0>
        <thead>
          <tr>
             <th class="counter">#</th>
             <th>Tracking ID</th>
             <th>Sender Name</th>
             <th>Phone</th>
             <th>Land/Air..</th>
             <th>Liquid/Solid</th>
             <th>Weight (Kg/Lbs) </th>
             <th>Status</th>
             {% if shipments.count > 0%}
             <th>X</th>
             {% endif %}
          </tr>
       </thead>
       <tbody>
         {% for shipment in shipments %}
         
        <tr>
         <td class="counter"><p>{{forloop.counter}}</p></td>
         <td><a href="{{shipment.get_update_url}}">{{shipment.tracking_id}}</a></td>
         <td><p>{{shipment.sender_name|title}}</p></td>
         <td><p>{{shipment.sender_phone}}</p></td>
         <td><p>{{shipment.transport_method|title}}</p></td>
         <td><p>{{shipment.substance_type|title}}</p></td>
         <td><p>{{shipment.units|title}}({{shipment.unit_of_measurement|title}})</p></td>
         <td><p>{{shipment.status|title}}</p></td>
         <td>
          {% if shipment.staff == user %}
          <button type="button" class="pointer del-btn" onclick="showModal('{{shipment.tracking_id}}')">X</button>
          {% endif %}
        </td>
       </tr>
       {% empty %}
        <tr class="empty-tr">
            <td colspan="7">
              {{empty_txt}}
              <a class="empty-cart" href="{% url 'logistics:add-shipment' %}">Add Shipment
              </a>
            </td>
        </tr>
       {% endfor %}
      </tbody>
      </table>
    </div>

    <div class="sm_tab_table">
      <table cellspacing=0>
        <thead>
          <tr>
             <th>Tracking ID</th>
             <th>Sender Name</th>
             <th>Phone</th>
             <th>Status</th>
             {% if shipments.count > 0%}
             <th>X</th>
             {% endif %}
          </tr>
       </thead>
       <tbody>
         {% for shipment in shipments %}
         
        <tr>
         <td><a href="">{{shipment.tracking_id}}aaaa</a></td>
         <td><p>{{shipment.sender_name|title}}</p></td>
         <td><p>{{shipment.sender_phone}}</p></td>
         <td><p>{{shipment.status|title}}</p></td>
         <td>
          {% if shipment.staff == user %}
          <button type="button" class="pointer del-btn" onclick="showModal('{{shipment.tracking_id}}')">X</button>
          {% endif %}
        </td>
       </tr>
       {% empty %}
        <tr class="empty-tr">
            <td colspan="7">
              You have not made any shipment. 
              <a class="empty-cart" href="{% url 'logistics:add-shipment' %}">Add Shipment
              </a>
            </td>
        </tr>
       {% endfor %}
      </tbody>
      </table>
    </div>

    <div class="mobile_table">
      {% for shipment in shipments %}
      <div class="mobile-table-div">
        <div class="rows">
          <h4>Tracking ID :</h4>
          <a href="">{{shipment.tracking_id}}</a>
        </div>
        <div class="rows">
          <h4>Sender Name : </h4>
          <p>{{shipment.sender_name|title}}</p>
        </div>
        <div class="rows">
          <h4>Receiever Name : </h4>
          <p>{{shipment.reciever_name|title}}</p>
        </div>
        <div class="rows n-bdr">
          <h4>Status : </h4>
          <p>{{shipment.status|title}}</p>
        </div>
        <div class="flex btn-div">
          <a href="" class="txt-ctr d-block update-link">update</a>
          {% if shipment.staff == user %}
          <button class="txt-ctr pointer d-block sm-table-del"  onclick="showModal('{{shipment.tracking_id}}')">Delete</button>
          {% endif %}
        </div>
      </div>  
      {% empty %}
      <div class="empty-div">
        No shipment registered. 
          <a class="empty-cart" href="{% url 'logistics:add-shipment' %}">Add Shipment
          </a>
      </div>
      {% endfor %}
      
    </div>

  </div>
</div>

<div class="inner-container">
  
</div>

{% endblock content %}

{% block js %} 

{% comment %} Code to delete Shipment from server {% endcomment %}
<script>

  function showModal(slug) {
    const url = "{% url 'logistics:delete-shipment' 0 %}".replace('0', slug);
    document.getElementById("refCode").innerText = `"${slug}"`;
    const aTag = document.getElementById("deleteShipmentLink");
    aTag.setAttribute('href', url);
    modalBox.style.display = "flex";
    body.style.overflow = "hidden";
  }

</script>

{% endblock js %}